<a href="https://colab.research.google.com/github/andresf-sierra/python_iq_meetup/blob/master/python_iq_introduccion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Introducción y Conceptos Básicos de Python para IQ**

####  ***Andrés F. Sierra***

  *Estudiante de Ingeniería Química y Ciencia de Datos*

  *Campus Rep 2021* 

  *Diplomado en Análisis de Datos y Machine Learning en Python*
  

 <!-- badges: start -->
[![Andres Sierra](https://img.shields.io/badge/LinkedIn-blue?&logoColor=white)](https://www.linkedin.com/in/andresf-sierra/) 
[![Andres Sierra](https://img.shields.io/badge/GitHub-green?&logoColor=white)](https://github.com/andresf-sierra)
<!-- badges: end -->

# 1) Introducción a Google Colab


**Colaboratory**, o mejor conocido como **Colab**, provee de un entorno interactivo a nivel de **archivo**. Dentro de él podrás **escribir** y **ejecutar código** python de una forma **sencilla** y **colaborativa** en tiempo real **sin** ninguna **configuración** extra.

El componente de trabajo **clave** en **Colab** son los **notebooks**, también conocidos como libretas interactivas o bloc de notas. Un notebook es una herramienta en la que puedes combinar **código ejecutable** y **texto enriquecido** en un sólo lugar. Además, podrás incluir **imágenes**, **HTML**, **LaTeX** y mucho más.

---




## Ejecución y edición de celdas

###  Celdas de código

A continuación encontrarás una **celda de código** en la que podrás ejecutar una sencilla instrucción en `Python`





In [ ]:
print("Curso basico de phyton")

Curso basico de phyton


Interactuar con las **celdas de código** es tan sencillo como dar clic en ella y presionar `Command/Ctrl + Enter`para **ejecutarla** y simplemente `escribir` para **editarla**.

> Edita, ejecuta, observa y repite. Ese es el ciclo de trabajo en los **notebooks**.

Ahora hagamos una conversión de unas sencillas unidades, números de segundos en un día

In [6]:
secs_per_day = 60*60*24 #[seg*min*h]

print(secs_per_day)

86400


In [7]:
print(f'Un día tiene {secs_per_day} segundos')

Un día tiene 86400 segundos


Hola, estoy contento con mis primeros pasos en el aprendizaje de Phyton


He ejecutado mis primeras celdas de **Python** en **Colab**

Hola, ya di mis primeros pasos en **Colab**

# 2) Introducción a Python

### Variables

Los nombres de las variables en Python pueden contener caracteres alfanuméricos a-z, A-Z, 0-9 y algunos caracteres especiales como _. Los nombres de las variables deben comenzar con una letra.

Entre las características más destacables de las sesiones interactivas dentro de los notebooks es que las variables que definas en una celda pueden ser utilizadas después en otras:

**Asignamos** a dos variables un texto (*string*)

In [ ]:
mi_primera_variable = "Esta es mi primera variable"
mi_segunda_variable = "esta es mi segunda variable"

In [ ]:
print(f'{mi_primera_variable} {mi_segunda_variable}')

Esta es mi primera variable esta es mi segunda variable


También podemos agrupar el resultado en una nueva variable.

In [ ]:
mi_tercera_variable = mi_primera_variable + mi_segunda_variable
print(mi_tercera_variable)

Esta es mi primera variableesta es mi segunda variable


### Tipos de variables

En Python, los tipos fundamentales son 





1.   Enteros (int).
2.   Punto flotante (float).
3.   Buleanos (boolean)
4.   Cadena de caracteres (strings).

Veamos algunos ejemplos de estos tipos:

Enteros (int)

In [ ]:
edad = 20  
type(edad)

int

Punto flotante (float)

In [ ]:
estatura = 1.70
type(estatura)

float

Buleanos (boolean)

In [ ]:
aprendo_python = True
type(aprendo_python)


bool

Cadenas de texto (Strings)

In [ ]:
materia_dificil = "Fenomenos de Transporte"
type(materia_dificil) 

str

## Operadores y comparadores

| Operadores      | aritméticos |
|-----------------|-------------|
| Suma            |      +      |
| Resta           |      -      |
| Multiplicación  |      *      |
| División        |      /      |
| División entera | //          |
| Negación        | -           |
| Exponente       | **          |
| Módulo          | %           |





In [ ]:
2/2 

0



*   Los buleanos están conectados o precedidos por palabras como `and`, `not`, `or`.

In [ ]:
True and False

False

In [ ]:
not False

True

In [ ]:
True or False

True

*   Operadores de comparación `>`, `<`, `>=`(mayor o igual), `<=` (menor o igual), `==` (igual), `!=`(no igual) y `is` (identico).


In [ ]:
2!=3

True

In [ ]:
2>3,2<2

(False, False)

In [ ]:
4<=4,4>=4

(True, True)

In [ ]:
#igual a
[3.0,2]==[3,2]

True

In [ ]:
# Not equal to

2 != 5

True

## Funciones
Una función es un bloque de código organizado y reutilizable, usado para realizar una única acción relacionada. Las funciones proporcionan una mejor modularidad para su aplicación y un alto grado de reutilización del código.


>`def Nombre(arg1,arg2,...):`
>> `sentencias`

De esta forma, se representa una función normalmente.

Ahora, definamos la función exponencial de $a^{b}$

- Primero, definimos la función, le ponemos un nombre e ingresamos los argumentos que tiene esta función.
- Siguiendo sintáxis, escribimos la escuación que representa a nuestra función.
- Retornamos el valor de la función para que haga la operación
- Por último llamamos la función con los valores de los parámetros de entrada que deseamos.

La sentencia *return* termina la función,  devolviendo opcionalmente uno o varios valores. 

In [2]:
def Exp(a,b):
  exp = a**b
  return exp

print(Exp(2,2)) 

4


La sentencia *return* termina la función,  devolviendo opcionalmente uno o varios valores. Una declaración de retorno sin argumentos es lo mismo que devolver *none* (como en el caso anterior)

In [3]:
def Exp(a,b):
  return a**b

print(Exp(2,2))  

4


In [4]:
def Exp2(a,b):
  return a**b, a**b+1, a**b+2

print(Exp2(2,2))  

(4, 5, 6)


---


# 3) Ejemplos en la Ingeniería Química

### Definamos y evaluemos una función

Como aplicación usemos la ecuación de **Arrhenius** que determina cómo la rapidez de una reacción química se ve afectada por la temperatura y que se define como:
\begin{equation}
k=A\exp\left(-\frac{E_a}{k_B T}\right),
\end{equation}
en donde $A$ es una constante, $E_a$ es la energía de activación, $k_B$ es la constante de Bolztmann y $T$ es la temperatura. 

---

Crearemos una función para la ecuación de **Arrehenius** que tendrá cómo parámetro de entrada la Temperatura y la energía de activación.

Recordemos siempre importar las librerías.
 

In [ ]:
import numpy as np

Una vez creada la función con `def` + `nombre_función`  y pasémos sus argumentos o parámetros `temp, actEnergia`, procedemos a definir los valores que conocemos de la ecuación, los cuales son $k_{B}$ y $A$. 
Y por último, retornamos la evaluación de la función.

In [ ]:
def arrhenius(temp, actEnergia):
    kB = 1.380449e-23 #[J/K]
    A = 1
    return A*np.exp(- actEnergia/(kB*temp))

Ahora, hacemos una prueba con Temperatura de 100 y con una energía de activación de 1e-21

In [ ]:
arrhenius(100, 1e-21)

0.4846142874547784

Ahora vamos a crear una conjunto de temperaturas a evaluar en la función que hemos creado. Para esto usaremos el comando `np.linspace` el cual nos ayuda a crear una arreglo numérico. Este arreglo numérico tendrá la característica que empezará a 250, terminará a 450 y en ese rango solo quiero 50 valores. O sea, `inicio=250, final=450, n=50`. Una vez creado el arreglo numérico de las tempraturas, evaluamos en nuestra función. 


In [ ]:
temp_array = np.linspace(250, 450, 50)
arrhenius(temp_array, 1e-21)

array([0.74844258, 0.75193454, 0.75533162, 0.75863758, 0.76185603,
       0.76499035, 0.76804379, 0.7710194 , 0.77392011, 0.77674869,
       0.77950778, 0.78219988, 0.78482741, 0.78739263, 0.78989772,
       0.79234477, 0.79473575, 0.79707256, 0.79935701, 0.80159083,
       0.80377567, 0.80591313, 0.80800473, 0.8100519 , 0.81205605,
       0.81401852, 0.81594059, 0.81782347, 0.81966837, 0.82147641,
       0.82324867, 0.82498621, 0.82669004, 0.82836112, 0.83000038,
       0.83160872, 0.83318701, 0.83473608, 0.83625672, 0.83774971,
       0.8392158 , 0.8406557 , 0.84207011, 0.8434597 , 0.84482511,
       0.84616697, 0.84748587, 0.84878241, 0.85005714, 0.85131061])

Cómo podemos observar, al evaluar el arreglo numérico del rango de temperaturas dentro de la función creada para la ecuación de Arrhenius, obtenemos fácilmente la evaluación de todas las tempraturas dadas con un valor de energía de activación.

Si deseo comprobar si en verdad mi array cumple con las especifiaciones que le he dado, ejecuto el método `len()`

In [ ]:
len(temp_array)

50

Ahora podemos crear un arreglo numérico de las energías de activación utilizando el mismo método anterior.


In [ ]:
energias_array = np.linspace(-10,10,50)*1e-21
arrhenius(273, energias_array) 

array([14.20348186, 12.74554168, 11.43725421, 10.26325811,  9.20976879,
        8.26441666,  7.41610177,  6.65486359,  5.97176397,  5.35878226,
        4.80872108,  4.31512186,  3.87218895,  3.47472163,  3.11805301,
        2.79799524,  2.51079033,  2.25306606,  2.02179632,  1.81426565,
        1.62803732,  1.4609247 ,  1.31096564,  1.17639937,  1.05564589,
        0.94728735,  0.85005145,  0.7627965 ,  0.68449798,  0.61423654,
        0.5511872 ,  0.49460967,  0.44383963,  0.39828097,  0.35739875,
        0.32071296,  0.28779284,  0.25825186,  0.23174317,  0.2079555 ,
        0.18660956,  0.16745471,  0.15026604,  0.13484173,  0.12100068,
        0.10858036,  0.09743495,  0.08743357,  0.07845881,  0.07040527])

In [ ]:
arrhenius(temp_array, energias_array)

array([18.1307239 , 15.40497079, 13.15660703, 11.29171092,  9.73666802,
        8.43341742,  7.33588973,  6.40731941,  5.61820353,  4.94474141,
        4.36763464,  3.87115878,  3.44244119,  3.0708961 ,  2.74778044,
        2.46584272,  2.21904433,  2.00233701,  1.81148462,  1.64291957,
        1.4936268 ,  1.3610496 ,  1.24301283,  1.13766014,  1.04340241,
        0.95887523,  0.88290381,  0.81447379,  0.75270702,  0.69684124,
        0.64621316,  0.60024418,  0.55842836,  0.52032231,  0.48553657,
        0.4537283 ,  0.42459508,  0.39786958,  0.37331501,  0.35072127,
        0.32990153,  0.31068938,  0.29293634,  0.27650966,  0.2612905 ,
        0.24717227,  0.23405921,  0.22186517,  0.2105125 ,  0.19993116])

---


### Volumen molar y factor de compresibilidad a partir de la ecuación de Van Der Waals

#### **Problema:**

Utilice la ecuación de estado de Van der Waals, dada por:

$$\left(P+\frac{a}{V^2}\right)\left(V-b\right)=RT$$

$$a=\frac{27}{64}\left(\frac{R^2T^2_c}{P_c}\right)$$

$$b=\frac{RT_c}{8P_c}$$

Dónde




* $P$ es la presión en atm
* $V$ es el volumen molar en litros/g-mol
* $T$ es la temperatura en Kelvin
* $R$ es la constante de gas ideal (R = 0.08206 atm.litros/g-mol.K)
* $T_c$ es la temperatura crítica (405.5 K para el amoniaco)
* $P_c$ es la presión crítica (111.3 atm para el amoniaco)


La presión reducida es:

$$P_r=\frac{P}{P_c}$$

Y la compresibilidad es:

$$Z=\frac{PV}{RT}$$

- **Calcule** el volumen molar y el factor de compresibilidad del amoníaco gaseoso a 56 atm y 450 K utilizando la ecuación de estado de Van der Waals.





---
**Solución**

Como tenemos que reordenar la ecuación, podemos utilizar el paquete sympy para que haga el álgebra por nosotros:



In [ ]:
import sympy

In [ ]:
P,V,N,R,T,a,b,Pc,Pr,Tc,Z = sympy.symbols('P V N R T a b Pc Pr Tc Z')

In [ ]:
eq1 = sympy.Eq((P+a/V**2)*(V-b),R*T) #Van der Waals
a_def = sympy.Eq(27/64*(R**2*Tc**2/Pc),a) #Factor a
b_def = sympy.Eq(R*Tc/(8*Pc),b) #Factor b


Confirmemos que hemos introducido las ecuaciones

In [ ]:
eq1


Eq((P + a/V**2)*(V - b), R*T)

In [ ]:
a_def


Eq(0.421875*R**2*Tc**2/Pc, a)

In [ ]:
b_def

Eq(R*Tc/(8*Pc), b)

Podemos obtener los valores de $a$ y $b$ con la sustitución:

In [ ]:
eq1_subs = eq1.subs({a:27/64*(R**2*Tc**2/Pc),b:R*Tc/(8*Pc)})
eq1_subs

Eq((P + 0.421875*R**2*Tc**2/(Pc*V**2))*(V - R*Tc/(8*Pc)), R*T)

Solución para a)

Sustituye la presión y la temperatura dadas para la parte a:

In [ ]:

eq1_subs_part_a = eq1_subs.subs({P:56,R:0.08206,T:450,Pc:111.3,Tc:405.5})

A continuación, podemos sustituir los otros valores, y resolver para $V$

In [ ]:
root = sympy.solveset(eq1_subs_part_a,symbol = V, domain=sympy.S.Reals)
root.args[0]

0.574891913557151

Resolviendo para $Z$

In [ ]:

(P*V/(R*T)).subs({P:56,R:0.08206,T:450,V:root.args[0]})

0.871826770633966

Repositorio para los notebooks y scripts usados en el Meetup de Introducción y Conceptos Básicos de Python para Ingenieros Químicos, realizado con Platzi Campus Rep